efsblog/urls.py
from django.contrib import admin
from django.conf.urls import include,url
from django.urls import path
from django.contrib.auth import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
]

portfolio/urls.py
from django.conf.urls import url
from . import views
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'portfolio'
urlpatterns = [

    path('', views.home, name='home'),
    url(r'^home/$', views.home, name='home'),
    path('customer_list', views.customer_list, name='customer_list'),
    path('customer/<int:pk>/edit/', views.customer_edit, name='customer_edit'),
    path('customer/<int:pk>/delete/', views.customer_delete, name='customer_delete'),
    path('customer/<int:pk>/portfolio/', views.portfolio, name='portfolio'),
    path('stock_list', views.stock_list, name='stock_list'),
    path('stock/create/', views.stock_new, name='stock_new'),
    path('stock/<int:pk>/edit/', views.stock_edit, name='stock_edit'),
    path('stock/<int:pk>/delete/', views.stock_delete, name='stock_delete'),
    path('investment_list', views.investment_list, name='investment_list'),
    path('investment/create/', views.investment_new, name='investment_new'),
    path('investment/<int:pk>/edit/', views.investment_edit, name='investment_edit'),
    path('investment/<int:pk>/delete/', views.investment_delete, name='investment_delete'),
    path('mutualfund_list', views.mutualfund_list, name='mutualfund_list'),
    path('mutualfund/create/', views.mutualfund_new, name='mutualfund_new'),
    path('mutualfund/<int:pk>/edit/', views.mutualfund_edit, name='mutualfund_edit'),
    path('mutualfund/<int:pk>/delete/', views.mutualfund_delete, name='mutualfund_delete'),
    url(r'^customers_json/', views.CustomerList.as_view()),
    url(r'^register/$', views.register, name='register'),
    url(r'^register/success/$', views.register_success, name='success'),

]

urlpatterns = format_suffix_patterns(urlpatterns)

portfolio/forms.py
from django import forms
from .models import Customer, Stock, Investment, Mutualfund
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
import re

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('cust_number', 'name', 'address', 'city', 'state', 'zipcode', 'email', 'cell_phone',)

class StockForm(forms.ModelForm):
   class Meta:
       model = Stock
       fields = ('customer', 'symbol', 'name', 'shares', 'purchase_price', 'purchase_date',)

class InvestmentForm(forms.ModelForm):
   class Meta:
       model = Investment
       fields = ('customer', 'category', 'description', 'acquired_value', 'acquired_date', 'recent_value','recent_date',)

class MutualfundForm(forms.ModelForm):
    class Meta:
        model = Mutualfund
        fields = ('customer', 'category', 'description', 'shares', 'purchased_value', 'purchased_date', 'recent_value', 'recent_date',)

class RegistrationForm(forms.Form):
    username = forms.CharField(label='Username', max_length=30)
    email = forms.EmailField(label='Email')
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput())
    password2 = forms.CharField(label='Password (Again)',  widget=forms.PasswordInput())

    #password validation
    def clean_password2(self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1 == password2:
                return password2
        raise forms.ValidationError('Passwords do not match.')

    def clean_username(self):
        username = self.cleaned_data['username']
        if not re.search(r'^\w+$', username):
            raise forms.ValidationError('Username can only contain alphanumeric characters and the underscore.')
        try:
            User.objects.get(username=username)
        except ObjectDoesNotExist:
            return username
        raise forms.ValidationError('Username is already taken.')

portfolio/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from .models import *
from .forms import *
from django.db.models import Sum
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .serializers import CustomerSerializer
from django.views.decorators.csrf import csrf_protect
from django.core.mail import send_mail

#registration
#from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django.template import RequestContext

from django.contrib.auth.forms import PasswordChangeForm
from django.template.response import TemplateResponse
from django.shortcuts import resolve_url
from django.urls import reverse, reverse_lazy
from django.utils.deprecation import (
    RemovedInDjango21Warning,
)
import warnings
from django.contrib.auth import (
    REDIRECT_FIELD_NAME, get_user_model, login as auth_login,
    logout as auth_logout, update_session_auth_hash,
)

now = timezone.now()
def home(request):
   return render(request, 'portfolio/home.html',
                 {'portfolio': home})

@login_required()
def customer_list(request):
    customer = Customer.objects.filter(created_date__lte=timezone.now())
    return render(request, 'portfolio/customer_list.html',
                 {'customers': customer})

@login_required()
def customer_edit(request, pk):
   customer = get_object_or_404(Customer, pk=pk)
   if request.method == "POST":
       # update
       form = CustomerForm(request.POST, instance=customer)
       if form.is_valid():
           customer = form.save(commit=False)
           customer.updated_date = timezone.now()
           customer.save()
           customer = Customer.objects.filter(created_date__lte=timezone.now())
           return render(request, 'portfolio/customer_list.html',
                         {'customers': customer})
   else:
        # edit
       form = CustomerForm(instance=customer)
   return render(request, 'portfolio/customer_edit.html', {'form': form})

@login_required()
def customer_delete(request, pk):
   customer = get_object_or_404(Customer, pk=pk)
   customer.delete()
   return redirect('portfolio:customer_list')

@login_required
def stock_list(request):
   stocks = Stock.objects.filter(purchase_date__lte=timezone.now())
   return render(request, 'portfolio/stock_list.html',
                 {'stocks': stocks})

@login_required
def stock_new(request):
   if request.method == "POST":
       form = StockForm(request.POST)
       if form.is_valid():
           stock = form.save(commit=False)
           stock.created_date = timezone.now()
           stock.save()
           stocks = Stock.objects.filter(purchase_date__lte=timezone.now())
           return render(request, 'portfolio/stock_list.html',
                         {'stocks': stocks})
   else:
       form = StockForm()
       # print("Else")
   return render(request, 'portfolio/stock_new.html',
                 {'form': form})

@login_required
def stock_edit(request, pk):
   stock = get_object_or_404(Stock, pk=pk)
   if request.method == "POST":
       form = StockForm(request.POST, instance=stock)
       if form.is_valid():
           stock = form.save()
           # stock.customer = stock.id
           stock.updated_date = timezone.now()
           stock.save()
           stocks = Stock.objects.filter(purchase_date__lte=timezone.now())
           return render(request, 'portfolio/stock_list.html', {'stocks': stocks})
   else:
       # print("else")
       form = StockForm(instance=stock)
   return render(request, 'portfolio/stock_edit.html',
                 {'form': form})

@login_required()
def stock_delete(request, pk):
   stock = get_object_or_404(Stock, pk=pk)
   stock.delete()
   return redirect('portfolio:stock_list')

@login_required
def investment_list(request):
   investments = Investment.objects.filter(acquired_date__lte=timezone.now())
   return render(request, 'portfolio/investment_list.html',
                 {'investments': investments})

@login_required
def investment_new(request):
   if request.method == "POST":
       form = InvestmentForm(request.POST)
       if form.is_valid():
           investment = form.save(commit=False)
           investment.created_date = timezone.now()
           investment.save()
           investments = Investment.objects.filter(acquired_date__lte=timezone.now())
           return render(request, 'portfolio/investment_list.html',
                         {'investments': investments})
   else:
       form = InvestmentForm()
       # print("Else")
   return render(request, 'portfolio/investment_new.html',
                 {'form': form})

@login_required
def investment_edit(request, pk):
   investment = get_object_or_404(Investment, pk=pk)
   if request.method == "POST":
       form = InvestmentForm(request.POST, instance=investment)
       if form.is_valid():
           investment = form.save()
           # stock.customer = stock.id
           investment.updated_date = timezone.now()
           investment.save()
           investments = Investment.objects.filter(acquired_date__lte=timezone.now())
           return render(request, 'portfolio/investment_list.html', {'investments': investments})
   else:
       # print("else")
       form = InvestmentForm(instance=investment)
   return render(request, 'portfolio/investment_edit.html',
                 {'form': form})

@login_required()
def investment_delete(request, pk):
   investment = get_object_or_404(Investment, pk=pk)
   investment.delete()
   return redirect('portfolio:investment_list')

@login_required
def mutualfund_list(request):
    mutualfunds = Mutualfund.objects.filter( purchased_date__lte=timezone.now())
    return render(request, 'portfolio/mutualfund_list.html' , {'mutualfunds': mutualfunds})

@ login_required
def mutualfund_new(request):
    if request.method == "POST" :
        form = MutualfundForm(request.POST)
        if form.is_valid():
            mutualfund = form.save(commit=False)
            mutualfund.created_date = timezone.now()
            mutualfund.save()
            mutualfunds = Mutualfund.objects.filter( purchased_date__lte=timezone.now())
            return render(request, 'portfolio/mutualfund_list.html', {'mutualfunds': mutualfunds})
    else :
        form = MutualfundForm()
        # print("Else")
        return render(request, 'portfolio/mutualfund_new.html', {'form': form})


@ login_required
def mutualfund_edit(request, pk):
    mutualfund = get_object_or_404(Mutualfund, pk=pk)
    if request.method == "POST":
        form = MutualfundForm(request.POST, instance=mutualfund)
        if form.is_valid():
            mutualfund = form.save()
           # investment.customer = investment.id
            mutualfund.updated_date = timezone.now()
            mutualfund.save()
            mutualfunds = Mutualfund.objects.filter(purchased_date__lte=timezone.now())
            return render(request, 'portfolio/mutualfund_list.html', {'mutualfunds': mutualfunds})
    else:
        # print("else")
        form = MutualfundForm(instance=mutualfund)
        return render(request, 'portfolio/mutualfund_edit.html', {'form': form})


@ login_required
def mutualfund_delete(request, pk):
    mutualfund = get_object_or_404(Mutualfund, pk =pk)
    mutualfund.delete()
    mutualfunds = Mutualfund.objects.filter( purchased_date__lte=timezone.now())
    return render(request, 'portfolio/mutualfund_list.html', { 'mutualfunds': mutualfunds})

@login_required
def portfolio(request,pk):
   customer = get_object_or_404(Customer, pk=pk)
   customers = Customer.objects.filter(created_date__lte=timezone.now())
   investments =Investment.objects.filter(customer=pk)
   stocks = Stock.objects.filter(customer=pk)
   mutualfunds = Mutualfund.objects.filter(customer=pk)
   sum_recent_value = Investment.objects.filter(customer=pk).aggregate(Sum('recent_value'))
   sum_acquired_value = Investment.objects.filter(customer=pk).aggregate(Sum('acquired_value'))
   #overall_investment_results = sum_recent_value - sum_acquired_value
   # Initialize the value of the stocks
   sum_current_stocks_value = 0
   sum_of_initial_stock_value = 0

   # Loop through each stock and add the value to the total
   for stock in stocks:
        sum_current_stocks_value += stock.current_stock_value()
        sum_of_initial_stock_value += stock.initial_stock_value()

   return render(request, 'portfolio/portfolio.html', {'customers': customers,
                                                       'investments': investments,
                                                       'stocks': stocks,
                                                       'mutualfunds': mutualfunds,
                                                       'sum_acquired_value': sum_acquired_value,
                                                       'sum_recent_value': sum_recent_value,
                                                       #'overall_investment_results': overall_investment_results,
                                                       'sum_current_stocks_value': sum_current_stocks_value,
                                                       'sum_of_initial_stock_value': sum_of_initial_stock_value,
                                                       })

# List at the end of the views.py
# Lists all customers
class CustomerList(APIView):

    def get(self,request):
        customers_json = Customer.objects.all()
        serializer = CustomerSerializer(customers_json, many=True)
        return Response(serializer.data)

@csrf_protect
def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = User.objects.create_user(username=form.cleaned_data['username'],
                                            password=form.cleaned_data['password1'],

portfolio/templates/portfolio/base.html
{% load staticfiles %}

<html lang="en">
<head>
    <title>Eagle Financial Services</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }

        /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
        .row.content {
            height: 450px
        }

        /* Set gray background color and 100% height */
        .sidenav {
            padding-top: 20px;
            background-color: #f1f1f1;
            height: 100%;
        }

        /* Set black background color, white text and some padding */
        footer {
            background-color: #555;
            color: white;
            padding: 15px;
        }

        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
            .sidenav {
                height: auto;
                padding: 15px;
            }

            .row.content {
                height: auto;
            }
        }
    </style>
</head>
<body id="app-layout">
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#myNavbar">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
            <a class="navbar-brand" href="/">
                Eagle Financial Services
            </a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'portfolio:home' %}">Home</a></li>
                <li><a href="{% url 'portfolio:customer_list' %}">Customers</a></li>
               <li><a href="{% url 'portfolio:investment_list' %}">Investments</a></li>
                <li><a href="{% url 'portfolio:stock_list' %}">Stocks</a></li>
                <li><a href="{% url 'portfolio:mutualfund_list' %}">Mutualfunds</a></li>

            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'logout' %}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                    <li><a href="{% url 'portfolio:register' %}">Register</a></li>
                    <li><a href="{% url 'password_reset' %}">Reset Password</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="content container">
    <div class="row">
        <div class="col-md-8">
            {% block content %}
                <div class="links">
                    <!-- Example row of columns -->
                    <div class="row">
                        <div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static "images/customer.jpg" %}" alt="customer"/>
                                <div class="caption">
                                    <h2>Customer</h2>
                                    <p>We see our success in our customers success, it gives us an immense pleasure when
                                        our
                                        advises
                                        turn out to be fruitful. </p>
                                    {% if user.is_authenticated %}
                                        <p><a class="btn btn-default" href="{% url 'portfolio:customer_list' %}"
                                              role="button">View
                                            details &raquo;</a></p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static "images/nonstock.jpg" %}" alt="non-stock"/>
                                <div class="caption">
                                    <h2>Non-Stock Investments</h2>
                                    <p>Our team also provides advises for Non-Stock investments.</p>
                                    <p><a class="btn btn-default" href="{% url 'portfolio:investment_list' %}"
                                           role="button">View
                                        details &raquo;</a></p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static "images/stocks.jpg" %}" alt="stocks"/>
                                <div class="caption">
                                    <h2>Stock Portfolio</h2>
                                    <p>Our Stock portfolios vary across industries.</p>
                                    <p><a class="btn btn-default" href="{% url 'portfolio:stock_list' %}" role="button">View
                                        details &raquo;</a></p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static "images/mutualfund.jpg" %}" alt="stocks"/>
                                <div class="caption">
                                    <h2>Mutualfund Portfolio</h2>
                                    <p>Our Mutualfund portfolios vary across industries.</p>
                                    <p><a class="btn btn-default" href="{% url 'portfolio:mutualfund_list' %}" role="button">View
                                        details &raquo;</a></p>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

portfolio/templates/portfolio/customer_edit.html
{% extends 'portfolio/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Edit Customer</h1>
    <form method="POST" class="customer-form">{% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

portfolio/templates/portfolio/customer_list.html
{% extends 'portfolio/base.html' %}
{% block content %}

    <html>
    <head>
        <meta charset="UTF-8">
        <title>Eagle Financial</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Eagle Financial Services, your Midwest Financial Services Partner.
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Customer Information</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Customer Number</th>
                <th>Name</th>
                <th>Address</th>
                <th>City</th>
                <th>State</th>
                <th>Zip</th>
                <th>Primary Email</th>
                <th>Cell Phone</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for customer in customers %}
                <tr>
                    <td>{{ customer.cust_number }}</td>
                    <td>{{ customer.name }}</td>
                    <td>{{ customer.address }}</td>
                    <td>{{ customer.city }}</td>
                    <td>{{ customer.state }}</td>
                    <td>{{ customer.zipcode }}</td>
                    <td>{{ customer.email }}</td>
                    <td>{{ customer.cell_phone }}</td>
                    <td><a href="{% url 'portfolio:customer_edit' pk=customer.pk %}" class="btn btn-warning">Edit</a>
                    <td><a href="{% url 'portfolio:customer_delete' pk=customer.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                    </td>
                    <td><a href="{% url 'portfolio:portfolio' pk=customer.pk %}"
                           class="btn btn-primary">Portfolio</a>

                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
    </body>
    </html>
{% endblock %}

portfolio/templates/portfolio/investment_delete.html
{% extends 'portfolio/base.html' %}
{% block body_block %}
    <h1>Delete {{ customer.name }}?</h1>
    <h1>Delete {{ investment.name }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'portfolio:home' pk=investment.cust_number %} ">Cancel</a>
    </form>
{% endblock %}

portfolio/templates/portfolio/investment_edit.html
{% extends 'portfolio/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Edit Investment</h1>
    <form method="POST" class="investment-form">{% csrf_token %}
         {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

portfolio/templates/portfolio/investment_list.html
{% extends 'portfolio/base.html' %}
{% block content %}
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Eagle Financial</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Eagle Financial Services, your Midwest Financial Services Partner.
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Non-Stock Investment Information</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Customer number</th>
                <th>Category</th>
                <th>Description</th>
                <th>Acquired Value</th>
                <th>Acquired Date</th>
                <th>Recent Value</th>
                <th>Recent Date</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for investment in investments %}
                <tr>
                    <td>{{ investment.customer }}</td>
                    <td>{{ investment.category }}</td>
                    <td>{{ investment.description }}</td>
                    <td>{{ investment.acquired_value }}</td>
                    <td>{{ investment.acquired_date }}</td>
                    <td>{{ investment.recent_value }}</td>
                    <td>{{ investment.recent_date }}</td>
                    <td><a href="{% url 'portfolio:investment_edit' pk=investment.pk %}"
                           class="btn btn-warning">Edit</a></td>
                    <td><a href="{% url 'portfolio:investment_delete' pk=investment.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
     <div class="row">
           <a href="{% url 'portfolio:investment_new' %}" class="row"><span
                    class="btn btn-primary">Add Stock</span></a>
        </div>
    </div>
    </body>
    </html>
{% endblock %}

portfolio/templates/portfolio/mutualfund_edit.html
{% extends 'portfolio/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Edit Mutualfund</h1>
    <form method="POST" class="mutualfund-form">{% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

portfolio/templates/portfolio/mutualfund_list.html
{% extends 'portfolio/base.html' %}
{% block content %}

    <html>
    <head>
        <meta charset="UTF-8">
        <title>Eagle Financial</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Eagle Financial Services, your Midwest Financial Services Partner.
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Mutualfund Information</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Customer</th>
                <th>Customer Name</th>
                <th>Category</th>
                <th>Description</th>
                <th>Shares</th>
                <th>Purchased Value</th>
                <th>Purchased Date</th>
                <th>Recent Value</th>
                <th>Recent Date</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for mutualfund in mutualfunds %}
                <tr>
                    <td>{{ mutualfund.customer }}</td>
                    <td>{{ mutualfund.customer.name}}</td>
                    <td>{{ mutualfund.category }}</td>
                    <td>{{ mutualfund.description }}</td>
                    <td>{{ mutualfund.shares }}</td>
                    <td>{{ mutualfund.purchased_value }}</td>
                    <td>{{ mutualfund.purchased_date }}</td>
                    <td>{{ mutualfund.recent_value }}</td>
                    <td>{{ mutualfund.recent_date }}</td>
                    <td><a href="{% url 'portfolio:mutualfund_edit' pk=mutualfund.pk %}"
                           class="btn btn-warning">Edit</a></td>
                    <td><a href="{% url 'portfolio:mutualfund_delete' pk=mutualfund.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
     <div class="row">
            <a href="{% url 'portfolio:mutualfund_new' %}" class="row"><span
                    class="btn btn-primary">Add Mutualfund</span></a>
        </div>
    </div>
    </body>
    </html>
{% endblock %}